---
- name: Install firewalld package on CentOS
  ansible.builtin.yum:
    name: firewalld
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure firewalld service is enabled and started on CentOS
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started
  when: ansible_os_family == 'RedHat'

- name: Allow SSH connections on CentOS
  ansible.builtin.firewalld:
    service: ssh
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_os_family == 'RedHat'
